export const inProgressComments = [
  "<p>Investigating the issue and reviewing application logs.</p>",
  "<p>Started analyzing the root cause and checking recent changes.</p>",
  "<p>Working on reproducing the issue in the local environment.</p>",
  "<p>Reviewing API flow and debugging the affected module.</p>",
  "<p>Checking database records and validating edge cases.</p>",
  "<p>Analyzing user scenario to identify where the flow is breaking.</p>",
  "<p>Tracing the issue through service layer and verifying conditions.</p>",
  "<p>Reviewing validation logic and related business rules.</p>",
  "<p>Debugging the reported issue and testing multiple scenarios.</p>",
  "<p>Inspecting recent deployments to identify potential impact.</p>",
  "<p>Analyzing logs from staging environment for further clarity.</p>",
  "<p>Reviewing recent commits to detect potential regressions.</p>",
  "<p>Testing different input combinations to isolate the issue.</p>",
  "<p>Verifying API request and response payload structure.</p>",
  "<p>Cross-checking issue with similar past incidents.</p>",
  "<p>Monitoring system behavior under specific edge conditions.</p>",
  "<p>Replicating issue in QA environment for confirmation.</p>",
  "<p>Validating configuration settings impacting the flow.</p>",
  "<p>Coordinating with team members for additional context.</p>",
  "<p>Performing step-by-step debugging to narrow down the cause.</p>",
];

export const resolvedComments = [
  "<p>Fix implemented and verified locally. Ready for testing.</p>",
  "<p>Issue resolved after correcting validation logic. Please verify.</p>",
  "<p>Applied necessary changes and deployed the fix. Kindly test.</p>",
  "<p>Root cause identified and resolved. Awaiting QA confirmation.</p>",
  "<p>Bug fixed and unit tested successfully.</p>",
  "<p>Code updated to handle edge cases properly. Ready for validation.</p>",
  "<p>Resolved by correcting API response handling logic.</p>",
  "<p>Implemented fix and performed regression testing.</p>",
  "<p>Changes deployed successfully. Please proceed with QA testing.</p>",
  "<p>Issue addressed and verified in development environment.</p>",
  "<p>Patch applied and functionality validated across scenarios.</p>",
  "<p>Correction implemented and smoke testing completed.</p>",
  "<p>Optimized logic and confirmed expected behavior.</p>",
  "<p>Bug resolved after configuration update.</p>",
  "<p>Fix validated against acceptance criteria.</p>",
  "<p>Resolved with proper exception handling added.</p>",
  "<p>Issue corrected and performance verified.</p>",
  "<p>All impacted modules tested post-fix implementation.</p>",
  "<p>Solution deployed and monitored for stability.</p>",
  "<p>Confirmed resolution and updated documentation accordingly.</p>",
];

export const raComments = [
  "<p>Reviewed the requirement document and started analyzing the functional scope.</p>",
  "<p>Analyzing business requirements and validating acceptance criteria.</p>",
  "<p>Discussing requirement clarity with stakeholders to avoid ambiguity.</p>",
  "<p>Evaluating feasibility and identifying potential gaps in requirements.</p>",
  "<p>Reviewing use cases and mapping them to system functionality.</p>",
  "<p>Identifying edge cases and documenting assumptions.</p>",
  "<p>Validating requirement flow and checking dependency impacts.</p>",
  "<p>Performing impact analysis on existing modules based on new requirements.</p>",
  "<p>Documenting observations and preparing queries for clarification.</p>",
  "<p>Requirement analysis completed and findings shared with the team.</p>",
  "<p>Analyzing integration touchpoints mentioned in requirements.</p>",
  "<p>Reviewing workflow diagrams for logical consistency.</p>",
  "<p>Cross-verifying requirement scope with business objectives.</p>",
  "<p>Identifying missing scenarios in functional documentation.</p>",
  "<p>Clarifying edge conditions with product owner.</p>",
  "<p>Preparing functional breakdown for development reference.</p>",
  "<p>Documenting constraints and limitations.</p>",
  "<p>Reviewing compliance requirements related to feature.</p>",
  "<p>Mapping requirement to technical feasibility.</p>",
  "<p>Consolidating feedback and finalizing RA notes.</p>",
];

export const raInProgressComments = [
  "<p>Started reviewing the requirement document for clarity and completeness.</p>",
  "<p>Analyzing functional and non-functional requirements.</p>",
  "<p>Identifying ambiguities and documenting clarification points.</p>",
  "<p>Validating business flow against the provided requirements.</p>",
  "<p>Reviewing acceptance criteria for completeness.</p>",
  "<p>Checking requirement dependencies across modules.</p>",
  "<p>Discussing scenarios with the product team for better understanding.</p>",
  "<p>Evaluating technical feasibility of the proposed solution.</p>",
  "<p>Preparing impact analysis report.</p>",
  "<p>Analyzing edge cases and documenting observations.</p>",
  "<p>Reviewing workflow consistency across modules.</p>",
  "<p>Validating requirement assumptions.</p>",
  "<p>Checking API dependency implications.</p>",
  "<p>Assessing scalability considerations in requirements.</p>",
  "<p>Listing open queries for stakeholder discussion.</p>",
  "<p>Reviewing constraints and boundary conditions.</p>",
  "<p>Comparing requirement changes with previous versions.</p>",
  "<p>Analyzing user journey described in documentation.</p>",
  "<p>Preparing draft functional summary.</p>",
  "<p>Aligning requirement scope with sprint goals.</p>",
];

export const raResolvedComments = [
  "<p>Requirement analysis completed and no major gaps identified.</p>",
  "<p>All clarifications addressed and requirements finalized.</p>",
  "<p>Impact analysis completed and shared with stakeholders.</p>",
  "<p>Requirement scope validated and ready for development.</p>",
  "<p>Document updated with necessary clarifications.</p>",
  "<p>All functional scenarios verified and approved.</p>",
  "<p>Dependencies identified and communicated to respective teams.</p>",
  "<p>Requirements reviewed and confirmed for implementation.</p>",
  "<p>Acceptance criteria validated and approved.</p>",
  "<p>Requirement analysis phase completed successfully.</p>",
  "<p>All stakeholder queries resolved.</p>",
  "<p>Final requirement baseline established.</p>",
  "<p>Updated documentation shared with team.</p>",
  "<p>Requirement sign-off received.</p>",
  "<p>Functional scope locked for development.</p>",
  "<p>Impact summary circulated among teams.</p>",
  "<p>Requirement gaps addressed successfully.</p>",
  "<p>Clarifications incorporated into final document.</p>",
  "<p>Dependencies tracked and finalized.</p>",
  "<p>RA documentation archived for sprint reference.</p>",
];

export const raQaReviewComments = [
  "<p>Reviewed the requirement document from QA perspective; test scenarios are feasible.</p>",
  "<p>Requirements validated for test coverage; no major gaps identified.</p>",
  "<p>QA review completed; acceptance criteria are clear and testable.</p>",
  "<p>Reviewed functional flow and identified a few clarification points for better test coverage.</p>",
  "<p>Requirement document evaluated; additional edge cases suggested.</p>",
  "<p>QA analysis completed and feedback shared regarding missing validation scenarios.</p>",
  "<p>Requirements reviewed; dependencies and negative scenarios documented.</p>",
  "<p>Testability review completed; minor updates requested before sign-off.</p>",
  "<p>All critical scenarios verified from QA standpoint.</p>",
  "<p>RA-QA review completed and ready for development phase.</p>",
  "<p>Edge case scenarios recommended for better coverage.</p>",
  "<p>Regression impact areas identified.</p>",
  "<p>Test data requirements documented.</p>",
  "<p>Reviewed requirement flow for automation feasibility.</p>",
  "<p>Test scenario mapping completed.</p>",
  "<p>Non-functional requirement coverage validated.</p>",
  "<p>QA queries addressed successfully.</p>",
  "<p>Acceptance criteria aligned with QA standards.</p>",
  "<p>Risk areas highlighted for testing focus.</p>",
  "<p>QA sign-off provided post-review.</p>",
];

export const designInProgressComments = [
  "<p>Working on initial wireframes based on the provided requirements.</p>",
  "<p>Designing UI components aligned with the latest brand guidelines.</p>",
  "<p>Creating responsive layouts for desktop and mobile views.</p>",
  "<p>Preparing mockups for stakeholder review.</p>",
  "<p>Incorporating user experience improvements into the current design.</p>",
  "<p>Design flow is being structured to ensure better usability.</p>",
  "<p>Updating layout structure as per recent feedback.</p>",
  "<p>Refining visual hierarchy and typography for clarity.</p>",
  "<p>Aligning color scheme and spacing with design system standards.</p>",
  "<p>Working on interactive prototype for smoother user journey validation.</p>",
  "<p>Designing alternate layout concepts for evaluation.</p>",
  "<p>Improving accessibility considerations in UI.</p>",
  "<p>Adjusting spacing and grid alignment.</p>",
  "<p>Preparing assets for review session.</p>",
  "<p>Revising navigation structure for clarity.</p>",
  "<p>Updating UI components as per feedback.</p>",
  "<p>Testing design responsiveness across devices.</p>",
  "<p>Enhancing micro-interactions for better UX.</p>",
  "<p>Validating usability improvements internally.</p>",
  "<p>Optimizing visual consistency across screens.</p>",
];

export const designReviewComments = [
  "<p>Design reviewed and minor UI alignment adjustments suggested.</p>",
  "<p>Layout consistency verified; feedback shared for spacing improvements.</p>",
  "<p>Typography and color contrast reviewed; recommended refinements.</p>",
  "<p>User flow reviewed; suggested simplification for better usability.</p>",
  "<p>Responsive behavior validated across breakpoints.</p>",
  "<p>Design reviewed and shared comments for component consistency.</p>",
  "<p>Navigation structure reviewed; suggested enhancement for clarity.</p>",
  "<p>Prototype reviewed; minor interaction improvements recommended.</p>",
  "<p>Accessibility considerations reviewed; feedback shared.</p>",
  "<p>Design feedback documented and communicated to the team.</p>",
  "<p>Iconography alignment adjustments suggested.</p>",
  "<p>Consistency across forms validated.</p>",
  "<p>Minor visual hierarchy tweaks recommended.</p>",
  "<p>Spacing inconsistencies highlighted.</p>",
  "<p>Color contrast improvements suggested.</p>",
  "<p>UX improvement areas documented.</p>",
  "<p>Component behavior reviewed for clarity.</p>",
  "<p>Layout responsiveness feedback shared.</p>",
  "<p>Interactive elements reviewed.</p>",
  "<p>Final review notes shared with design team.</p>",
];

export const designResolvedComments = [
  "<p>Final design completed and shared for implementation.</p>",
  "<p>All design feedback incorporated successfully.</p>",
  "<p>Design approved and ready for development phase.</p>",
  "<p>Mockups finalized and uploaded to shared repository.</p>",
  "<p>UI/UX design completed and validated with stakeholders.</p>",
  "<p>All revisions implemented; design locked for development.</p>",
  "<p>Prototype finalized and ready for handoff.</p>",
  "<p>Design system components updated and approved.</p>",
  "<p>Final visual assets delivered to development team.</p>",
  "<p>Design phase completed successfully.</p>",
  "<p>Accessibility updates applied.</p>",
  "<p>Responsive issues resolved.</p>",
  "<p>Stakeholder approval received.</p>",
  "<p>Final UI kit delivered.</p>",
  "<p>Interaction flow confirmed.</p>",
  "<p>Design documentation updated.</p>",
  "<p>Assets optimized for development use.</p>",
  "<p>UI consistency validated across screens.</p>",
  "<p>Feedback cycle closed successfully.</p>",
  "<p>Design handoff meeting completed.</p>",
];

export const codeReviewInProgressComments = [
  "<p>Code submitted for review. Evaluating logic and structure.</p>",
  "<p>Reviewing implementation against the defined requirements.</p>",
  "<p>Analyzing code quality, readability, and best practice adherence.</p>",
  "<p>Validating edge cases and error handling implementation.</p>",
  "<p>Checking API integration and response handling logic.</p>",
  "<p>Reviewing database queries and performance considerations.</p>",
  "<p>Verifying adherence to project coding standards.</p>",
  "<p>Assessing modularization and reusability of components.</p>",
  "<p>Reviewing validation logic and security practices.</p>",
  "<p>Performing peer review before merging into main branch.</p>",
  "<p>Checking naming conventions and structure consistency.</p>",
  "<p>Evaluating scalability considerations in implementation.</p>",
  "<p>Reviewing test coverage adequacy.</p>",
  "<p>Inspecting exception handling blocks.</p>",
  "<p>Validating input sanitization mechanisms.</p>",
  "<p>Analyzing asynchronous flow correctness.</p>",
  "<p>Ensuring proper logging implementation.</p>",
  "<p>Checking dependency updates impact.</p>",
  "<p>Reviewing performance bottlenecks.</p>",
  "<p>Assessing code maintainability aspects.</p>",
];

export const codeReviewChangesRequestedComments = [
  "<p>Minor refactoring suggested for better readability.</p>",
  "<p>Please optimize the function to reduce redundant calls.</p>",
  "<p>Additional validation required for edge case handling.</p>",
  "<p>Code duplication observed; recommend extracting reusable logic.</p>",
  "<p>Error handling needs improvement for failed API scenarios.</p>",
  "<p>Security concern identified; input sanitization required.</p>",
  "<p>Performance optimization recommended for database queries.</p>",
  "<p>Variable naming can be improved for clarity.</p>",
  "<p>Kindly update comments/documentation for better understanding.</p>",
  "<p>Requested minor updates before approval.</p>",
  "<p>Improve null/undefined checks.</p>",
  "<p>Consider breaking large function into smaller modules.</p>",
  "<p>Optimize API call sequencing logic.</p>",
  "<p>Add missing unit test cases.</p>",
  "<p>Improve error logging clarity.</p>",
  "<p>Follow consistent formatting standards.</p>",
  "<p>Enhance validation before database write.</p>",
  "<p>Reduce nested conditional complexity.</p>",
  "<p>Handle promise rejection properly.</p>",
  "<p>Address linting warnings before merge.</p>",
];

export const codeReviewApprovedComments = [
  "<p>Code review completed and approved for merge.</p>",
  "<p>Implementation aligns with requirements. Approved.</p>",
  "<p>Code structure is clean and follows standards. Good to merge.</p>",
  "<p>All review comments addressed. Approved.</p>",
  "<p>Logic validated and tested. Ready for deployment.</p>",
  "<p>No major issues identified. Approved from review side.</p>",
  "<p>Changes verified and confirmed. Approved.</p>",
  "<p>Best practices followed. Merge approved.</p>",
  "<p>Code quality looks good. Proceeding with approval.</p>",
  "<p>Reviewed and approved after necessary updates.</p>",
  "<p>All edge cases handled properly.</p>",
  "<p>Validation and error handling confirmed.</p>",
  "<p>Test coverage sufficient for merge.</p>",
  "<p>Performance considerations addressed.</p>",
  "<p>Security checks validated.</p>",
  "<p>Code readability is satisfactory.</p>",
  "<p>No blocking issues found.</p>",
  "<p>Implementation meets acceptance criteria.</p>",
  "<p>Approved after final verification.</p>",
  "<p>Ready to merge into main branch.</p>",
];